# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import pb_pb2 as pb__pb2

class AIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessAIRequest = channel.unary_unary(
                '/aipool.AIService/ProcessAIRequest',
                request_serializer=pb__pb2.AIRequest.SerializeToString,
                response_deserializer=pb__pb2.AIResponse.FromString,
                )


class AIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessAIRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessAIRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessAIRequest,
                    request_deserializer=pb__pb2.AIRequest.FromString,
                    response_serializer=pb__pb2.AIResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aipool.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessAIRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aipool.AIService/ProcessAIRequest',
            pb__pb2.AIRequest.SerializeToString,
            pb__pb2.AIResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
